config/routes.rb
Rails.application.routes.draw do
  root "pages#home"

  post "theme/toggle", to: "pages#toggle_theme", as: :toggle_theme
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def toggle_theme
    cookies[:theme] =
      cookies[:theme] == "dark" ? "light" : "dark"

    redirect_back fallback_location: root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="pl">
<head>
  <title><%= content_for(:title) || "Dark Mode App 2" %></title>

  <meta name="viewport" content="width=device-width,initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="mobile-web-app-capable" content="yes">

  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= yield :head %>

  <link rel="icon" href="/icon.png" type="image/png">
  <link rel="icon" href="/icon.svg" type="image/svg+xml">
  <link rel="apple-touch-icon" href="/icon.png">

  <%# JEDEN plik z Tailwindem (app.css -> @import "tailwindcss") %>
  <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
</head>

<body class="<%= "dark" if cookies[:theme] == "dark" %>">
<main>

  <%= yield %>

</main>
</body>
</html>

app/views/pages/home.html.erb
<div class="w-full h-screen bg-indigo-500 dark:bg-gray-900 flex items-center justify-center">
  <h1 class="text-7xl font-semibold text-indigo-50 dark:text-gray-400">
    Hello Variaty
  </h1>
</div>

<div class="absolute top-4 right-4">
  <%= button_to toggle_theme_path,
                method: :post,
                class: "transition hover:scale-110" do %>

    <% if cookies[:theme] == "dark" %>
      🌙
    <% else %>
      ☀️
    <% end %>

  <% end %>
</div>